# Generated by Django 2.2.18 on 2021-02-13 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('description', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('lastPurchasePrice', models.DecimalField(decimal_places=2, default=' ', max_digits=5)),
                ('lastPurchaseDate', models.DateTimeField(auto_now_add=True)),
                ('measurementType', models.CharField(default='g', max_length=10)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('description', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('instructions', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('servings', models.IntegerField(default='1')),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=' ', max_digits=5)),
                ('description', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ri_ingredient', to='QuickMenu.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ri_recipe', to='QuickMenu.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='QuickMenu.RecipeIngredient', to='QuickMenu.Ingredient'),
        ),
        migrations.CreateModel(
            name='MenuOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('offerPrice', models.DecimalField(decimal_places=2, default=' ', max_digits=5)),
                ('offeringStart', models.DateTimeField(auto_now_add=True)),
                ('offeringEnd', models.DateTimeField(auto_now_add=True)),
                ('quantiySold', models.IntegerField(default='0')),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='QuickMenu.Recipe')),
            ],
        ),
    ]
