# Generated by Django 2.2.18 on 2021-02-14 21:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='purchaseAmount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='lastPurchasePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuoffering',
            name='offerPrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5, null=True),
        ),
    ]
